
name: deployment

on:
  push:
    branches:
      - main
    paths:
      - 'Frontend_IS/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync build/ s3://${{ AWS_S3_BUCKET_NAME_STATIC_WEBSITE }} --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ AWS_ACCESS_KEY_GITHUB_ACTIONS }}
          AWS_SECRET_ACCESS_KEY: ${{ AWS_SECRET_KEY_GITHUB_ACTIONS }}

      - run: aws cloudfront create-invalidation --distribution-id ${{ AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
