name: deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '#deploy') }}
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        working-directory: ./Frontend_IS/
        run: npm install
      - name: build react
        working-directory: ./Frontend_IS/
        run: CI='' npm run build
      - uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_GITHUB_ACTIONS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_GITHUB_ACTIONS }}
          aws-region: "ap-northeast-1"
          aws-bucket: ${{ secrets.AWS_S3_BUCKET_NAME_STATIC_WEBSITE }}
          file-path: "./Frontend_IS/build/"
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: "/*"
          AWS_REGION: "ap-northeast-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_GITHUB_ACTIONS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_GITHUB_ACTIONS }}
