name: deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '#deploy') }}
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        working-directory: ./Frontend_IS/
        run: npm install
      - name: build react
        working-directory: ./Frontend_IS/
        run: CI='' npm run build
      - uses: shinyinc/action-aws-cli@v1.2
      - name: upload S3
        working-directory: ./Frontend_IS/
        run: |
          pwd
          aws s3 sync build s3://${{ secrets.AWS_S3_BUCKET_NAME_STATIC_WEBSITE }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_GITHUB_ACTIONS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_GITHUB_ACTIONS }}
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
